apiVersion: v1
kind: Pod
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  containers:
  - image: anakli/memcached:t1
    name: memcached
    imagePullPolicy: Always
    command: [ "/bin/sh" ]
    args: [ "-c", "taskset -c 0-1 ./memcached -t 2 -u memcache" ]
    resources:
      requests:
        memory: "8192Mi"
        cpu: "2"
      limits:
        memory: "8192Mi"
        cpu: "2"
  nodeSelector:
    cca-project-nodetype: "node-d-4core"
