apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: parsec-ferret
        imagePullPolicy: Always
        command: [ "/bin/sh" ]
        args: [ "-c", "taskset -c 2-3 ./run -a run -S parsec -p ferret -i native -n 2" ]
        resources:
          requests:
            memory: "7168Mi"
            cpu: "1.5"
          limits:
            memory: "7168Mi"
            cpu: "2"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-d-4core"
